# https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 20.x
          - 22.x
        browser:
          - chromium
          - firefox
          - webkit
    name: ${{ matrix.browser }} - Node ${{ matrix.node-version }}
    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - run: npm ci
      - run: npm run test:unit
      - run: npx playwright install --with-deps ${{ matrix.browser }}
      - run: npx playwright test --browser ${{ matrix.browser }}
