name: YAML Lint

on:
  pull_request:

jobs:
  yaml_lint:
    name: Run yamllint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: reviewdog/action-yamllint@v1
        with:
          fail_level: any
          filter_mode: nofilter
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check
